config/routes.rb
Rails.application.routes.draw do

  get 'champion/index'
  get 'champion', to: 'champion#index'
  get 'portflios/:id/report', to: 'portfolios#report', as: 'portfolio_report'
  resources :dividend_ranks
  resources :holdings

  resources :portfolios
  resources :holdings
  resources :stocks
  resources :industries
  resources :sectors
  get 'welcome/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/stocks/list', to: 'stocks#list', as: 'stock_list'
  get '/', to: 'welcome#index', as: 'home'
  get '/faq', to: 'application#faq', as: 'faq'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
end

app/models/holding.rb
class Holding < ApplicationRecord

  belongs_to :stock
  belongs_to :portfolio

  validates_presence_of :stock
  has_one :sector_id, :through => :stock

  def holding_symbol
    stock.try(:symbol)
  end

#  def holding_symbol=(symbol)
#    self.holding = Stock.find_by(symbol: symbol.split(" ")[0]) if symbol.present?
#  end

  def value
    quote = stock.quote
    return nil if quote.nil?
    price = quote["latest_price"]
    return nil if price.nil?
    return price.to_f * quantity
  end

  def cost
    return price
  end

  def div_value
    a = self.stock.dividend_ranks.last.new_rate
    return 0.0 if a.nil?
   a * self.quantity
  end
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  def index
    @grid = HoldingsGrid.new(grid_params) do |scope|
	    scope.where(portfolio_id: params[:portfolio_id]).page(params[:page])
    end
  end

  before_action :set_holding, only: [:show, :edit, :update, :destroy]

  # GET /holdings/1
  # GET /holdings/1.json
  def show
  end

  # GET /holdings/new
  def new
    @holding = Holding.new
    @holding.portfolio_id = params[:portfolio_id]
  end

  # GET /holdings/1/edit
  def edit
  end

  # POST /holdings
  # POST /holdings.json
  def create
    @holding_symbol = params[:holding][:holding_symbol]
    params[:holding].delete(:holding_symbol)
    @holding = Holding.new(holding_params)
    list = @holding_symbol.split()
    @holding.stock = Stock.find_by_symbol(list[0])

    respond_to do |format|
      if @holding.save
        format.html { redirect_to @holding.portfolio, notice: 'Holding was successfully created.' }
        format.json { render :show, status: :created, location: @holding }
      else
        format.html { render :new }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holdings/1
  # PATCH/PUT /holdings/1.json
  def update
    @holding_symbol = params[:holding][:holding_symbol]
    params[:holding].delete(:holding_symbol)
    @holding.stock = Stock.find_by_symbol(@holding_symbol.split()[0])

    respond_to do |format|
      if @holding.update(holding_params)
        format.html { redirect_to @holding.portfolio, notice: 'Holding was successfully updated.' }
        format.json { render :show, status: :ok, location: @holding }
      else
        format.html { render :edit }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holdings/1
  # DELETE /holdings/1.json
  def destroy
    portfolio = @holding.portfolio
    @holding.destroy
    respond_to do |format|
      format.html { redirect_to portfolio, notice: 'Holding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def grid_params
    params.fetch(:holdings_grid, {}).permit!
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holding
      @holding = Holding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holding_params
      params.require(:holding).permit(:stock_id, :stock_type, :price, :quantity, :date, :portfolio_id, :holding_symbol)
    end
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/views/holdings/_form.html.erb
<%= form_with(model: holding, local: true) do |form| %>
  <% if holding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(holding.errors.count, "error") %> prohibited this holding from being saved:</h2>

      <ul>
      <% holding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :holding_symbol, data: { autocomplete_source: stocks_path}, id: 'holding_holding_symbol' %>

  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :holding_price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :holding_quantity %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :holding_date %>
  </div>

    <%= form.hidden_field :portfolio_id, id: :holding_portfolio_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<script>
jQuery(function() {
  return $('#holding_holding_symbol').autocomplete({
    source: $('#holding_holding_symbol').data('autocomplete-source')
  });
});
</script>

app/views/holdings/edit.html.erb
<h1>Editing Holding</h1>

<%= render 'form', holding: @holding %>

<%= link_to 'Show', @holding %> |
<%= link_to 'Back', holdings_path %>

app/views/holdings/index.html.erb
<%= datagrid_form_for @grid, :method => :get, :url => holdings_path %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>

app/views/holdings/new.html.erb
<h1>New Holding</h1>

<%= render 'form', holding: @holding %>

<%= link_to 'Back', holdings_path %>

app/views/holdings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Holding:</strong>
  <%= link_to "#{@holding.stock.symbol} #{@holding.stock.name}", stock_path(@holding.stock) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @holding.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @holding.quantity %>
</p>

<p>
  <strong>Date:</strong>
  <%= @holding.date %>
</p>

<p>
  <strong>Portfolio:</strong>
  <%= @holding.portfolio.name %>
</p>

<%= link_to 'Edit', edit_holding_path(@holding) %> |
<%= link_to 'Back', holdings_path %>