config/routes.rb
Rails.application.routes.draw do

  get 'champion/index'
  get 'champion', to: 'champion#index'
  get 'portflios/:id/report', to: 'portfolios#report', as: 'portfolio_report'
  resources :dividend_ranks
  resources :holdings

  resources :portfolios
  resources :holdings
  resources :stocks
  resources :industries
  resources :sectors
  get 'welcome/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/stocks/list', to: 'stocks#list', as: 'stock_list'
  get '/', to: 'welcome#index', as: 'home'
  get '/faq', to: 'application#faq', as: 'faq'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  validates_presence_of :name

  has_many :holdings

  def value
    val = 0.0
    self.holdings.each do |stock|
      val += stock.value.to_f
    end
    return val
  end

  def cost
    val = 0.0
    self.holdings.each do |holding|
      val += holding.cost
    end
    return val
  end

  def div_value
    val = 0.0
    self.holdings.each do |holding|
      val += holding.div_value
    end
    return val
  end

  def contains?(symbol)
    holdings.select{|x| x.stock.symbol == symbol}
  end

  def symbols
    holdings.collect{|x| x.stock.symbol}.uniq
  end

  def sector_list
    sectors = {}
    holdings.each do |holding|
      sectors[holding.stock.sector.name] = 0 if sectors[holding.stock.sector.name].nil?
      sectors[holding.stock.sector.name] += 1
    end
    sectors
  end

  def industry_list
    industrys = {}
    holdings.each do |holding|
      industrys[holding.stock.industry.name] = 0 if industrys[holding.stock.industry.name].nil?
      industrys[holding.stock.industry.name] += 1
    end
    industrys
  end

  def pay_div(symbol)
    sum = 0.0
    holdings.map{|x| (x.stock.symbol == symbol ? sum += x.quantity : 0)}
    stock = Stock.find_by_symbol(symbol)
    div_rec = DividendRank.where(stock_id: stock.id).group_by_month(:date).last
    quantity = sum * div_rec.div_yield / div_rec.price
    new_holding = Holding.create(stock: stock, quantity: quantity, price: sum*div_rec.new_rate, date: div_rec.div_pay)
    holdings << new_holding
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_portfolio, only: [:report, :show, :edit, :update, :destroy]

  def report
    @comments = {}
    holdings = @portfolio.holdings.collect{|x| x.stock.id}

    drs = DividendRank.where("div_yield >= 3 and p_e <= 20 and price <= 100 and new_rate >= 0.65 and date = ? and stock_id not in (?)", DividendRank.last.date,holdings)

    drs_ids_a = drs.ids
    drs_ids_b = drs.ids

    @portfolio.holdings.each do |holding|
      drs_ids_a.each_with_index do |stk_a, index|
        s_a = DividendRank.find(stk_a)
        next if holdings.include?(s_a)

        index2 = index + 1

        while index2 < drs_ids_b.length do

          stk_b = drs_ids_b[index2] 
          next if stk_a == stk_b

          s_b = DividendRank.find(stk_b)
          next if holdings.include?(s_b)

          if holding.stock.dividend_ranks.last.price > s_a.price + s_b.price &&
            holding.stock.dividend_ranks.last.new_rate < s_a.new_rate + s_b.new_rate
            @comments[holding.stock.symbol] = {} if @comments[holding.stock.symbol].nil?
            @comments[holding.stock.symbol]["#{s_a.new_rate+s_b.new_rate}"] = {} if @comments[holding.stock.symbol]["#{s_a.new_rate+s_b.new_rate}"].nil?
            @comments[holding.stock.symbol]["#{s_a.new_rate+s_b.new_rate}"]["#{s_a.stock.symbol} #{s_b.stock.symbol}"] = "#{s_a.price} #{s_b.price}"
          end

          index2 += 1
        end
      end
    end
  end

  def index
    @grid = PortfoliosGrid.new(grid_params) do |scope|
      scope.where(:user_id => current_user.id).page(params[:page])
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @grid = HoldingsGrid.new(holdings_grid_params) do |scope|
      scope.where(portfolio_id: @portfolio.id).page(params[:page])
    end
    @sector_counts = @portfolio.sector_list
    @industry_counts = @portfolio.industry_list
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
    @portfolio.user = current_user
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def grid_params
    params.fetch(:portfolios_grid, {}).permit!
  end

  def holdings_grid_params
    params.fetch(:holdings_grid, {}).permit!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :user_id, :descripion, :start_date)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :portfolio_name %>
  </div>

    <%= form.hidden_field :user_id, id: :portfolio_user_id %>

  <div class="field">
    <%= form.label :descripion %>
    <%= form.text_area :descripion, id: :portfolio_descripion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<%= datagrid_form_for @grid, :method => :get, :url => portfolios_path %>
<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/report.html.erb
<table>
  <tr><th>Holding</th><th>Comments</th></tr>
<% @portfolio.holdings.each do |holding| -%>
  <tr><td><%= "#{holding.stock.symbol} #{holding.stock.name}" %></td>
    <td>
      <% unless @comments[holding.stock.symbol].nil? -%>
      <% @comments[holding.stock.symbol].keys.sort.reverse.each do |key| %>
      <%= key %> => 
      <%= @comments[holding.stock.symbol][key] %><br/>
    <% end -%>
    <% end -%>
    </td>
<% end -%>
</table>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %><br/>
  </p>
<div id="main-div">
<div id="grid-div">
  <p>
  <table>
    <tbody>
      <tr><td>
          <strong>Start date:</strong></td><td> <%= @portfolio.start_date %><br/>
        </td><td></td><td></td></tr>
      <tr><td>
          <strong>Cost:&nbsp;</strong></td><td><%= number_to_currency(@portfolio.cost) %><br/>
        </td><td>
            <strong>Holdings:&nbsp;</strong></td><td><%= @portfolio.holdings.count %><br/>
          </td><td></td></tr>
      <tr><td>
          <strong>Value:&nbsp;</strong></td><td><%= number_to_currency(@portfolio.value) %><br/>
        </td><td>
          <strong>Return on Cost:&nbsp;</strong></td><td><%= "%.2f" % ((@portfolio.value - @portfolio.cost) / @portfolio.cost * 100) %>%<br/>
        </td><td> </td></tr>
      <tr><td>
          <strong>Div Value:&nbsp;</strong></td><td><%= number_to_currency(@portfolio.div_value) %>
        </td><td>
  <strong>Return on Cost:&nbsp;</strong></td><td><%= "%.2f" % (@portfolio.div_value / @portfolio.cost * 100) %>%<br/>
        </td><td> </td></tr>
      <tr><td>
          <strong>Div Value(Yearly):&nbsp;</strong></td><td><%= number_to_currency(@portfolio.div_value*4) %>
        </td><td>
  <strong>Return on Cost(Yearly):&nbsp;</strong></td><td><%= "%.2f" % (@portfolio.div_value*4 / @portfolio.cost * 100) %>%<br/>
        </td><td> </td></tr>
    </tbody>
  </table>
  <%= link_to "Report", portfolio_report_path(@portfolio) %>
</p>

<p>
  <strong>Descripion:</strong>
  <%= @portfolio.descripion %>
</p>



<%#= line_chart @portfolio.holdings.map{|holding|
    {name: holding.stock.symbol, data: holding.stock.dividend_ranks.group_by_month(:date).pluck(:date,:price)}
}, points: false, width: "579px", height: "300px" %>
</div>
<div id="bar-chart-div">
<%= pie_chart @sector_counts, stacked: true %>
</div>
</div>

<div class="clear"></div>

<%#= datagrid_form_for @grid, :method => :get, :url => holdings_path %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>

<%= paginate(@grid.assets) %>

<%= link_to 'New Holding', new_holding_path(portfolio_id: @portfolio.id) %> | 
<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>