config/routes.rb
Rails.application.routes.draw do

  get 'champion/index'
  get 'champion', to: 'champion#index'
  get 'portflios/:id/report', to: 'portfolios#report', as: 'portfolio_report'
  resources :dividend_ranks
  resources :holdings

  resources :portfolios
  resources :holdings
  resources :stocks
  resources :industries
  resources :sectors
  get 'welcome/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/stocks/list', to: 'stocks#list', as: 'stock_list'
  get '/', to: 'welcome#index', as: 'home'
  get '/faq', to: 'application#faq', as: 'faq'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
end

app/models/sector.rb
class Sector < ApplicationRecord
     has_many :stocks
     has_many :industries
     has_many :dividend_ranks

	 validates_uniqueness_of :name
	 validates_presence_of :name
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_sector, only: [:show, :edit, :update, :destroy]


  def index
    @grid = SectorsGrid.new(grid_params) do |scope|
      scope.page(params[:page])
    end
    chart_list
  end

  def chart_list
    @chart_list = {}
    t = {}
    @grid.assets.each do |asset|
      cnt = asset.stocks.count
      t[asset.name] = cnt
    end
    z = t.sort_by {|_key, value| -value}
    z.each do |k,v|
      @chart_list[k] = v
    end
  end

  def chart_list2
    @chart_list = {}
    t = {}
    assets = []
    if !@grid.attributes[:sector_id].nil?
      assets = Stock.where(sector_id: @grid.attributes[:sector_id])
    elsif !@grid.attributes[:industry_id].nil?
      assets = Stock.where(industry_id: @grid.attributes[:industry_id])
    end
    assets.each do |asset|
      t[asset.industry.name] = 0 if t[asset.industry.name].nil?
      t[asset.industry.name] += 1
    end
    z = t.sort_by {|_key, value| -value}
    z.each do |k,v|
      @chart_list[k] = v
    end
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
    @industries_grid = IndustriesGrid.new(industry_grid_params.merge({:sector_id=>@sector.id})) do |scope|
       scope.page(params[:page])
    end
    @grid = StocksGrid.new(grid_params.merge({:show_industry=>true,:sector_id=>@sector.id})) do |scope|
       scope.page(params[:page])
    end
    chart_list2
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def grid_params
    params.fetch(:sectors_grid, {}).permit!
  end

  def industry_grid_params
    params.fetch(:industries_grid, {}).permit!
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_with(model: sector, local: true) do |form| %>
  <% if sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sector_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<h1>Editing Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/index.html.erb
<%#= datagrid_form_for @grid, :method => :get, :url => sectors_path %>

<%= bar_chart @chart_list, stacked: true %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>

app/views/sectors/new.html.erb
<h1>New Sector</h1>

<%= render 'form', sector: @sector %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sector.name %>
</p>

<div id="main-div">
<%#= datagrid_form_for @industries_grid, :method => :get, :url => industries_path %>

<div id="grid-div">
<%#= paginate(@industries_grid.assets) %>
<%= datagrid_table @industries_grid %>
<%#= paginate(@industries_grid.assets) %>
</div>
<div id="bar-chart-div">
<%= bar_chart @chart_list, stacked: true %>
</div>
</div>

<div class="clear"></div>

<%= datagrid_form_for @grid, :method => :get, :url => stocks_path %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>

<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>