config/routes.rb
Rails.application.routes.draw do

  get 'champion/index'
  get 'champion', to: 'champion#index'
  get 'portflios/:id/report', to: 'portfolios#report', as: 'portfolio_report'
  resources :dividend_ranks
  resources :holdings

  resources :portfolios
  resources :holdings
  resources :stocks
  resources :industries
  resources :sectors
  get 'welcome/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/stocks/list', to: 'stocks#list', as: 'stock_list'
  get '/', to: 'welcome#index', as: 'home'
  get '/faq', to: 'application#faq', as: 'faq'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
end

app/models/dividend_rank.rb
class DividendRank < ApplicationRecord
  belongs_to :stock
  belongs_to :sector
  belongs_to :industry

end

app/controllers/dividend_ranks_controller.rb
class DividendRanksController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_dividend_rank, only: [:show, :edit, :update, :destroy]

  # GET /dividend_ranks
  # GET /dividend_ranks.json
  def index
    @dividend_ranks = DividendRank.all
  end

  # GET /dividend_ranks/1
  # GET /dividend_ranks/1.json
  def show
    @grid = DividendRanksGrid.new(grid_params.merge({:stock_id => @dividend_rank.stock.id})) do |scope|
      scope.page(params[:page])
    end
  end

  # GET /dividend_ranks/new
  def new
    @dividend_rank = DividendRank.new
  end

  # GET /dividend_ranks/1/edit
  def edit
  end

  # POST /dividend_ranks
  # POST /dividend_ranks.json
  def create
    @dividend_rank = DividendRank.new(dividend_rank_params)

    respond_to do |format|
      if @dividend_rank.save
        format.html { redirect_to @dividend_rank, notice: 'Dividend rank was successfully created.' }
        format.json { render :show, status: :created, location: @dividend_rank }
      else
        format.html { render :new }
        format.json { render json: @dividend_rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dividend_ranks/1
  # PATCH/PUT /dividend_ranks/1.json
  def update
    respond_to do |format|
      if @dividend_rank.update(dividend_rank_params)
        format.html { redirect_to @dividend_rank, notice: 'Dividend rank was successfully updated.' }
        format.json { render :show, status: :ok, location: @dividend_rank }
      else
        format.html { render :edit }
        format.json { render json: @dividend_rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dividend_ranks/1
  # DELETE /dividend_ranks/1.json
  def destroy
    @dividend_rank.destroy
    respond_to do |format|
      format.html { redirect_to dividend_ranks_url, notice: 'Dividend rank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dividend_rank
      @dividend_rank = DividendRank.find(params[:id])
    end

    def grid_params
      params.fetch(:dividend_ranks_grid, {}).permit!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dividend_rank_params
      params.require(:dividend_rank).permit(:stock_id, :date, :ccc_seq, :price, :yield_years, :div_yield, :old_rate, :new_rate, :mr_inc, :ex_div, :div_record, :div_pay, :qtly_sched, :annual_div, :payout, :i_graham, :p_e, :fye_month, :ttm_eps, :peg_ratio, :ttm_p_sales, :mrq_p_book, :ttm_roe, :ty_growth, :ny_growth, :last_5_growth, :est_5_growth, :na, :mktcap, :inside_own, :debt_equity, :chowder_rule, :sector_id, :industry_id)
    end
end

app/helpers/dividend_ranks_helper.rb
module DividendRanksHelper
end

app/views/dividend_ranks/_form.html.erb
<%= form_with(model: dividend_rank, local: true) do |form| %>
  <% if dividend_rank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dividend_rank.errors.count, "error") %> prohibited this dividend_rank from being saved:</h2>

      <ul>
      <% dividend_rank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stock_id %>
    <%= form.number_field :stock_id, id: :dividend_rank_stock_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :dividend_rank_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dividend_ranks/edit.html.erb
<h1>Editing Dividend Rank</h1>

<%= render 'form', dividend_rank: @dividend_rank %>

<%= link_to 'Show', @dividend_rank %> |
<%= link_to 'Back', dividend_ranks_path %>

app/views/dividend_ranks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dividend Ranks</h1>

<table>
  <thead>
    <tr>
      <th>Stock</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dividend_ranks.each do |dividend_rank| %>
      <tr>
        <td><%= dividend_rank.stock_id %></td>
        <td><%= dividend_rank.date %></td>
        <td><%= link_to 'Show', dividend_rank %></td>
        <td><%= link_to 'Edit', edit_dividend_rank_path(dividend_rank) %></td>
        <td><%= link_to 'Destroy', dividend_rank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dividend Rank', new_dividend_rank_path %>

app/views/dividend_ranks/new.html.erb
<h1>New Dividend Rank</h1>

<%= render 'form', dividend_rank: @dividend_rank %>

<%= link_to 'Back', dividend_ranks_path %>

app/views/dividend_ranks/show.html.erb
<p id="notice"><%= notice %></p>

<table>
<tbody>
<tr>
  <th>Symbol</th>
  <th>Name</th>
  <th>Industry</th>
  <th>Sector</th>
</tr>

<tr>
  <td><%= @dividend_rank.stock.symbol %></td>
  <td><%= @dividend_rank.stock.name %></td>
  <td><%= @dividend_rank.stock.industry.name %></td>
  <td><%= @dividend_rank.stock.sector.name %></td>
</tr>

<tr>
  <th>Ccc seq</th>
  <th>Date</th>
  <th>Price</th>
  <th>Yield</th>
</tr>
<tr>
  <td><%= @dividend_rank.ccc_seq %></td>
  <td><%= @dividend_rank.date %></td>
  <td><%= @dividend_rank.price %></td>
  <td><%= @dividend_rank.div_yield %></td>
</tr>

  <tr>
  <th>Yield years</th>
	  <th colspan=3>Dividend Information</th>
  </tr>

<tr>
  <td><%= @dividend_rank.yield_years %></td>
  <th>Old rate</th>
  <th>New rate</th>
  <th>MR% inc</th>
</tr>

<tr>
  <th>Qtly Sched</th>
  <td><%= @dividend_rank.old_rate %></td>
  <td><%= @dividend_rank.new_rate %></td>
  <td><%= @dividend_rank.mr_inc %></td>
</tr>

<tr>
  <td><%= @dividend_rank.qtly_sched %></td>
  <th>Ex div</th>
  <th>Div record</th>
  <th>Div pay</th>
</tr>

<tr>
  <th>Annual div</th>
  <td><%= @dividend_rank.ex_div %></td>
  <td><%= @dividend_rank.div_record %></td>
  <td><%= @dividend_rank.div_pay %></td>
</tr>

<tr>
  <td><%= @dividend_rank.annual_div %></td>
	<td></td>
	<td></td>
	<td></td>
</tr>


<tr>
  <th>Payout</th>
  <th>P/E</th>
  <th>TTM EPS</th>
  <th>PEG Ratio</th>
</tr>

<tr>
  <td><%= @dividend_rank.payout %></td>
  <td><%= @dividend_rank.p_e %></td>
  <td><%= @dividend_rank.ttm_eps %></td>
  <td><%= @dividend_rank.peg_ratio %></td>
</tr>

<tr>
  <th>+/-% vs. Graham</th>
  <th>TTM P/Sales</th>
  <th>MRQ P/Book</th>
  <th>TTM ROE</th>
</tr>

<tr>
  <td><%= @dividend_rank.i_graham %></td>
  <td><%= @dividend_rank.ttm_p_sales %></td>
  <td><%= @dividend_rank.mrq_p_book %></td>
  <td><%= @dividend_rank.ttm_roe %></td>
</tr>

<tr>
  <th>TY growth</th>
  <th>NY growth</th>
  <th>Last 5 growth</th>
  <th>Est 5 growth</th>
</tr>

<tr>
  <td><%= @dividend_rank.ty_growth %></td>
  <td><%= @dividend_rank.ny_growth %></td>
  <td><%= @dividend_rank.last_5_growth %></td>
  <td><%= @dividend_rank.est_5_growth %></td>
</tr>

<tr>
  <th>Mktcap</th>
  <th>FYE month</th>
  <th>NA</th>
  <td></td>
</tr>

<tr>
  <td><%= @dividend_rank.mktcap %></td>
  <td><%= @dividend_rank.fye_month %></td>
  <td><%= @dividend_rank.na %></td>
  <td></td>
</tr>

<tr>
  <th>Inside own</th>
  <th>Debt equity</th>
  <th>Chowder rule</th>
  <td></td>
</tr>

<tr>
  <td><%= @dividend_rank.inside_own %></td>
  <td><%= @dividend_rank.debt_equity %></td>
  <td><%= @dividend_rank.chowder_rule %></td>
  <td></td>
</tr>
<tr>
<th><%= link_to 'Back', stock_path(@dividend_rank.stock) %></th>
  <td></td>
  <td></td>
  <td></td>
</tr>
	</tbody>
</table>
<%= datagrid_form_for @grid, :method => :get, :url => champion_path %>

<%= pie_chart @sector_counts %>

<%= paginate(@grid.assets) %>
<%= datagrid_table @grid %>
<%= paginate(@grid.assets) %>